[2025-09-10T03:00:34.136+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-10T03:00:34.206+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models manual__2025-09-10T02:55:08.278646+00:00 [queued]>
[2025-09-10T03:00:34.232+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models manual__2025-09-10T02:55:08.278646+00:00 [queued]>
[2025-09-10T03:00:34.233+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-10T03:00:34.252+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-10 02:55:08.278646+00:00
[2025-09-10T03:00:34.259+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3459) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-10T03:00:34.261+0000] {standard_task_runner.py:64} INFO - Started process 3460 to run task
[2025-09-10T03:00:34.265+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_run_models', 'run_dbt_models', 'manual__2025-09-10T02:55:08.278646+00:00', '--job-id', '1328', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp0xemd37_']
[2025-09-10T03:00:34.267+0000] {standard_task_runner.py:91} INFO - Job 1328: Subtask run_dbt_models
[2025-09-10T03:00:34.299+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-09-10T03:00:34.384+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_models.run_dbt_models manual__2025-09-10T02:55:08.278646+00:00 [running]> on host b5ea13053d47
[2025-09-10T03:00:34.665+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_run_models' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-10T02:55:08.278646+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-10T02:55:08.278646+00:00'
[2025-09-10T03:00:34.666+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-10T03:00:34.684+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-10T03:00:34.685+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /usr/app &&         dbt run --profiles-dir /usr/app\n        ']
[2025-09-10T03:00:34.698+0000] {subprocess.py:86} INFO - Output:
[2025-09-10T03:00:39.326+0000] {subprocess.py:93} INFO - [0m03:00:39  Running with dbt=1.7.9
[2025-09-10T03:00:40.096+0000] {subprocess.py:93} INFO - [0m03:00:40  Registered adapter: postgres=1.7.9
[2025-09-10T03:00:40.156+0000] {subprocess.py:93} INFO - [0m03:00:40  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-10T03:00:40.156+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-10T03:00:40.157+0000] {subprocess.py:93} INFO - - models.my_project.sources
[2025-09-10T03:00:40.189+0000] {subprocess.py:93} INFO - [0m03:00:40  Found 15 models, 7 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-09-10T03:00:40.194+0000] {subprocess.py:93} INFO - [0m03:00:40
[2025-09-10T03:00:40.455+0000] {subprocess.py:93} INFO - [0m03:00:40  Concurrency: 4 threads (target='dev')
[2025-09-10T03:00:40.456+0000] {subprocess.py:93} INFO - [0m03:00:40
[2025-09-10T03:00:40.480+0000] {subprocess.py:93} INFO - [0m03:00:40  1 of 15 START sql view model analytics.stg_AOV ................................. [RUN]
[2025-09-10T03:00:40.486+0000] {subprocess.py:93} INFO - [0m03:00:40  2 of 15 START sql view model analytics.stg_order_count_year .................... [RUN]
[2025-09-10T03:00:40.490+0000] {subprocess.py:93} INFO - [0m03:00:40  3 of 15 START sql view model analytics.stg_order_details ....................... [RUN]
[2025-09-10T03:00:40.494+0000] {subprocess.py:93} INFO - [0m03:00:40  4 of 15 START sql view model analytics.stg_order_items ......................... [RUN]
[2025-09-10T03:00:40.996+0000] {subprocess.py:93} INFO - [0m03:00:40  4 of 15 OK created sql view model analytics.stg_order_items .................... [[32mCREATE VIEW[0m in 0.47s]
[2025-09-10T03:00:41.020+0000] {subprocess.py:93} INFO - [0m03:00:41  1 of 15 OK created sql view model analytics.stg_AOV ............................ [[32mCREATE VIEW[0m in 0.52s]
[2025-09-10T03:00:41.024+0000] {subprocess.py:93} INFO - [0m03:00:41  2 of 15 OK created sql view model analytics.stg_order_count_year ............... [[32mCREATE VIEW[0m in 0.47s]
[2025-09-10T03:00:41.030+0000] {subprocess.py:93} INFO - [0m03:00:41  5 of 15 START sql view model analytics.stg_orders .............................. [RUN]
[2025-09-10T03:00:41.046+0000] {subprocess.py:93} INFO - [0m03:00:41  6 of 15 START sql view model analytics.stg_payments ............................ [RUN]
[2025-09-10T03:00:41.047+0000] {subprocess.py:93} INFO - [0m03:00:41  3 of 15 OK created sql view model analytics.stg_order_details .................. [[32mCREATE VIEW[0m in 0.55s]
[2025-09-10T03:00:41.062+0000] {subprocess.py:93} INFO - [0m03:00:41  7 of 15 START sql view model analytics.stg_products ............................ [RUN]
[2025-09-10T03:00:41.080+0000] {subprocess.py:93} INFO - [0m03:00:41  8 of 15 START sql table model analytics.AOV_chek ............................... [RUN]
[2025-09-10T03:00:41.511+0000] {subprocess.py:93} INFO - [0m03:00:41  5 of 15 OK created sql view model analytics.stg_orders ......................... [[32mCREATE VIEW[0m in 0.45s]
[2025-09-10T03:00:41.521+0000] {subprocess.py:93} INFO - [0m03:00:41  6 of 15 OK created sql view model analytics.stg_payments ....................... [[32mCREATE VIEW[0m in 0.45s]
[2025-09-10T03:00:41.538+0000] {subprocess.py:93} INFO - [0m03:00:41  9 of 15 START sql table model analytics.order_count_year ....................... [RUN]
[2025-09-10T03:00:41.543+0000] {subprocess.py:93} INFO - [0m03:00:41  10 of 15 START sql table model analytics.order_count_year+month_diff ........... [RUN]
[2025-09-10T03:00:41.544+0000] {subprocess.py:93} INFO - [0m03:00:41  7 of 15 OK created sql view model analytics.stg_products ....................... [[32mCREATE VIEW[0m in 0.46s]
[2025-09-10T03:00:41.563+0000] {subprocess.py:93} INFO - [0m03:00:41  11 of 15 START sql table model analytics.AVG_AOV_chek .......................... [RUN]
[2025-09-10T03:00:41.613+0000] {subprocess.py:93} INFO - [0m03:00:41  8 of 15 OK created sql table model analytics.AOV_chek .......................... [[32mSELECT 50[0m in 0.47s]
[2025-09-10T03:00:41.672+0000] {subprocess.py:93} INFO - [0m03:00:41  12 of 15 START sql table model analytics.orders_summary ........................ [RUN]
[2025-09-10T03:00:41.955+0000] {subprocess.py:93} INFO - [0m03:00:41  9 of 15 OK created sql table model analytics.order_count_year .................. [[32mSELECT 4[0m in 0.38s]
[2025-09-10T03:00:41.987+0000] {subprocess.py:93} INFO - [0m03:00:41  13 of 15 START sql table model analytics.AOV_EBITDA_COUNT ...................... [RUN]
[2025-09-10T03:00:42.044+0000] {subprocess.py:93} INFO - [0m03:00:42  10 of 15 OK created sql table model analytics.order_count_year+month_diff ...... [[32mSELECT 28[0m in 0.49s]
[2025-09-10T03:00:42.055+0000] {subprocess.py:93} INFO - [0m03:00:42  14 of 15 START sql table model analytics.AOV_category .......................... [RUN]
[2025-09-10T03:00:42.134+0000] {subprocess.py:93} INFO - [0m03:00:42  12 of 15 OK created sql table model analytics.orders_summary ................... [[32mSELECT 10000[0m in 0.45s]
[2025-09-10T03:00:42.181+0000] {subprocess.py:93} INFO - [0m03:00:42  15 of 15 START sql table model analytics.AOV_product_name ...................... [RUN]
[2025-09-10T03:00:42.189+0000] {subprocess.py:93} INFO - [0m03:00:42  11 of 15 OK created sql table model analytics.AVG_AOV_chek ..................... [[32mSELECT 16863[0m in 0.58s]
[2025-09-10T03:00:42.361+0000] {subprocess.py:93} INFO - [0m03:00:42  13 of 15 ERROR creating sql table model analytics.AOV_EBITDA_COUNT ............. [[31mERROR[0m in 0.36s]
[2025-09-10T03:00:42.373+0000] {subprocess.py:93} INFO - [0m03:00:42  14 of 15 ERROR creating sql table model analytics.AOV_category ................. [[31mERROR[0m in 0.29s]
[2025-09-10T03:00:42.406+0000] {subprocess.py:93} INFO - [0m03:00:42  15 of 15 ERROR creating sql table model analytics.AOV_product_name ............. [[31mERROR[0m in 0.21s]
[2025-09-10T03:00:42.456+0000] {subprocess.py:93} INFO - [0m03:00:42
[2025-09-10T03:00:42.458+0000] {subprocess.py:93} INFO - [0m03:00:42  Finished running 7 view models, 8 table models in 0 hours 0 minutes and 2.26 seconds (2.26s).
[2025-09-10T03:00:42.514+0000] {subprocess.py:93} INFO - [0m03:00:42
[2025-09-10T03:00:42.516+0000] {subprocess.py:93} INFO - [0m03:00:42  [31mCompleted with 3 errors and 0 warnings:[0m
[2025-09-10T03:00:42.518+0000] {subprocess.py:93} INFO - [0m03:00:42
[2025-09-10T03:00:42.520+0000] {subprocess.py:93} INFO - [0m03:00:42    Database Error in model AOV_EBITDA_COUNT (models/marts/AOV_EBITDA_COUNT.sql)
[2025-09-10T03:00:42.521+0000] {subprocess.py:93} INFO -   type "avr_order_value" does not exist
[2025-09-10T03:00:42.521+0000] {subprocess.py:93} INFO -   LINE 26: order by avr_order_value
[2025-09-10T03:00:42.522+0000] {subprocess.py:93} INFO -                     ^
[2025-09-10T03:00:42.522+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_EBITDA_COUNT.sql
[2025-09-10T03:00:42.525+0000] {subprocess.py:93} INFO - [0m03:00:42
[2025-09-10T03:00:42.526+0000] {subprocess.py:93} INFO - [0m03:00:42    Database Error in model AOV_category (models/marts/AOV_category.sql)
[2025-09-10T03:00:42.527+0000] {subprocess.py:93} INFO -   type "avr_order_value" does not exist
[2025-09-10T03:00:42.527+0000] {subprocess.py:93} INFO -   LINE 27: order by avr_order_value
[2025-09-10T03:00:42.527+0000] {subprocess.py:93} INFO -                     ^
[2025-09-10T03:00:42.528+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_category.sql
[2025-09-10T03:00:42.529+0000] {subprocess.py:93} INFO - [0m03:00:42
[2025-09-10T03:00:42.529+0000] {subprocess.py:93} INFO - [0m03:00:42    Database Error in model AOV_product_name (models/marts/AOV_product_name.sql)
[2025-09-10T03:00:42.530+0000] {subprocess.py:93} INFO -   type "avr_order_value" does not exist
[2025-09-10T03:00:42.530+0000] {subprocess.py:93} INFO -   LINE 28: order by avr_order_value
[2025-09-10T03:00:42.531+0000] {subprocess.py:93} INFO -                     ^
[2025-09-10T03:00:42.531+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_product_name.sql
[2025-09-10T03:00:42.531+0000] {subprocess.py:93} INFO - [0m03:00:42
[2025-09-10T03:00:42.533+0000] {subprocess.py:93} INFO - [0m03:00:42  Done. PASS=12 WARN=0 ERROR=3 SKIP=0 TOTAL=15
[2025-09-10T03:00:52.977+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-10T03:00:52.978+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-10T03:00:53.013+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-10T03:00:53.026+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_models, task_id=run_dbt_models, run_id=manual__2025-09-10T02:55:08.278646+00:00, execution_date=20250910T025508, start_date=20250910T030034, end_date=20250910T030053
[2025-09-10T03:00:53.060+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1328 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 1.; 3460)
[2025-09-10T03:00:53.101+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-10T03:00:53.161+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-10T03:00:53.172+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
