[2025-09-10T02:55:09.977+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-10T02:55:10.046+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models manual__2025-09-10T02:55:08.278646+00:00 [queued]>
[2025-09-10T02:55:10.069+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models manual__2025-09-10T02:55:08.278646+00:00 [queued]>
[2025-09-10T02:55:10.070+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-10T02:55:10.113+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-10 02:55:08.278646+00:00
[2025-09-10T02:55:10.125+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3417) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-10T02:55:10.128+0000] {standard_task_runner.py:64} INFO - Started process 3418 to run task
[2025-09-10T02:55:10.129+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_run_models', 'run_dbt_models', 'manual__2025-09-10T02:55:08.278646+00:00', '--job-id', '1325', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpedk6smm9']
[2025-09-10T02:55:10.131+0000] {standard_task_runner.py:91} INFO - Job 1325: Subtask run_dbt_models
[2025-09-10T02:55:10.165+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-09-10T02:55:10.252+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_models.run_dbt_models manual__2025-09-10T02:55:08.278646+00:00 [running]> on host b5ea13053d47
[2025-09-10T02:55:10.486+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_run_models' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-10T02:55:08.278646+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-10T02:55:08.278646+00:00'
[2025-09-10T02:55:10.487+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-10T02:55:10.502+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-10T02:55:10.502+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /usr/app &&         dbt run --profiles-dir /usr/app\n        ']
[2025-09-10T02:55:10.520+0000] {subprocess.py:86} INFO - Output:
[2025-09-10T02:55:14.600+0000] {subprocess.py:93} INFO - [0m02:55:14  Running with dbt=1.7.9
[2025-09-10T02:55:15.376+0000] {subprocess.py:93} INFO - [0m02:55:15  Registered adapter: postgres=1.7.9
[2025-09-10T02:55:15.456+0000] {subprocess.py:93} INFO - [0m02:55:15  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-10T02:55:15.457+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-10T02:55:15.458+0000] {subprocess.py:93} INFO - - models.my_project.sources
[2025-09-10T02:55:15.490+0000] {subprocess.py:93} INFO - [0m02:55:15  Found 15 models, 7 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-09-10T02:55:15.497+0000] {subprocess.py:93} INFO - [0m02:55:15
[2025-09-10T02:55:16.027+0000] {subprocess.py:93} INFO - [0m02:55:16  Concurrency: 4 threads (target='dev')
[2025-09-10T02:55:16.029+0000] {subprocess.py:93} INFO - [0m02:55:16
[2025-09-10T02:55:16.096+0000] {subprocess.py:93} INFO - [0m02:55:16  1 of 15 START sql view model analytics.stg_AOV ................................. [RUN]
[2025-09-10T02:55:16.103+0000] {subprocess.py:93} INFO - [0m02:55:16  2 of 15 START sql view model analytics.stg_order_count_year .................... [RUN]
[2025-09-10T02:55:16.107+0000] {subprocess.py:93} INFO - [0m02:55:16  3 of 15 START sql view model analytics.stg_order_details ....................... [RUN]
[2025-09-10T02:55:16.111+0000] {subprocess.py:93} INFO - [0m02:55:16  4 of 15 START sql view model analytics.stg_order_items ......................... [RUN]
[2025-09-10T02:55:18.042+0000] {subprocess.py:93} INFO - [0m02:55:18  4 of 15 OK created sql view model analytics.stg_order_items .................... [[32mCREATE VIEW[0m in 1.90s]
[2025-09-10T02:55:18.055+0000] {subprocess.py:93} INFO - [0m02:55:18  2 of 15 OK created sql view model analytics.stg_order_count_year ............... [[32mCREATE VIEW[0m in 1.90s]
[2025-09-10T02:55:18.058+0000] {subprocess.py:93} INFO - [0m02:55:18  1 of 15 OK created sql view model analytics.stg_AOV ............................ [[32mCREATE VIEW[0m in 1.93s]
[2025-09-10T02:55:18.076+0000] {subprocess.py:93} INFO - [0m02:55:18  3 of 15 OK created sql view model analytics.stg_order_details .................. [[32mCREATE VIEW[0m in 1.93s]
[2025-09-10T02:55:18.097+0000] {subprocess.py:93} INFO - [0m02:55:18  7 of 15 START sql view model analytics.stg_products ............................ [RUN]
[2025-09-10T02:55:18.101+0000] {subprocess.py:93} INFO - [0m02:55:18  5 of 15 START sql view model analytics.stg_orders .............................. [RUN]
[2025-09-10T02:55:18.107+0000] {subprocess.py:93} INFO - [0m02:55:18  6 of 15 START sql view model analytics.stg_payments ............................ [RUN]
[2025-09-10T02:55:18.134+0000] {subprocess.py:93} INFO - [0m02:55:18  8 of 15 START sql table model analytics.order_count_year ....................... [RUN]
[2025-09-10T02:55:18.871+0000] {subprocess.py:93} INFO - [0m02:55:18  7 of 15 OK created sql view model analytics.stg_products ....................... [[32mCREATE VIEW[0m in 0.73s]
[2025-09-10T02:55:18.884+0000] {subprocess.py:93} INFO - [0m02:55:18  9 of 15 START sql table model analytics.order_count_year+month_diff ............ [RUN]
[2025-09-10T02:55:18.890+0000] {subprocess.py:93} INFO - [0m02:55:18  5 of 15 OK created sql view model analytics.stg_orders ......................... [[32mCREATE VIEW[0m in 0.75s]
[2025-09-10T02:55:18.935+0000] {subprocess.py:93} INFO - [0m02:55:18  10 of 15 START sql table model analytics.AOV_chek .............................. [RUN]
[2025-09-10T02:55:19.031+0000] {subprocess.py:93} INFO - [0m02:55:19  6 of 15 OK created sql view model analytics.stg_payments ....................... [[32mCREATE VIEW[0m in 0.89s]
[2025-09-10T02:55:19.052+0000] {subprocess.py:93} INFO - [0m02:55:19  11 of 15 START sql table model analytics.orders_summary ........................ [RUN]
[2025-09-10T02:55:19.164+0000] {subprocess.py:93} INFO - [0m02:55:19  8 of 15 OK created sql table model analytics.order_count_year .................. [[32mSELECT 4[0m in 1.00s]
[2025-09-10T02:55:19.196+0000] {subprocess.py:93} INFO - [0m02:55:19  12 of 15 START sql table model analytics.AOV_EBITDA_COUNT ...................... [RUN]
[2025-09-10T02:55:19.496+0000] {subprocess.py:93} INFO - [0m02:55:19  12 of 15 ERROR creating sql table model analytics.AOV_EBITDA_COUNT ............. [[31mERROR[0m in 0.29s]
[2025-09-10T02:55:19.541+0000] {subprocess.py:93} INFO - [0m02:55:19  13 of 15 START sql table model analytics.AOV_category .......................... [RUN]
[2025-09-10T02:55:19.656+0000] {subprocess.py:93} INFO - [0m02:55:19  9 of 15 OK created sql table model analytics.order_count_year+month_diff ....... [[32mSELECT 28[0m in 0.72s]
[2025-09-10T02:55:19.697+0000] {subprocess.py:93} INFO - [0m02:55:19  10 of 15 OK created sql table model analytics.AOV_chek ......................... [[32mSELECT 50[0m in 0.74s]
[2025-09-10T02:55:19.725+0000] {subprocess.py:93} INFO - [0m02:55:19  14 of 15 START sql table model analytics.AOV_product_name ...................... [RUN]
[2025-09-10T02:55:19.839+0000] {subprocess.py:93} INFO - [0m02:55:19  15 of 15 START sql table model analytics.AVG_AOV_chek .......................... [RUN]
[2025-09-10T02:55:19.854+0000] {subprocess.py:93} INFO - [0m02:55:19  11 of 15 OK created sql table model analytics.orders_summary ................... [[32mSELECT 10000[0m in 0.76s]
[2025-09-10T02:55:20.096+0000] {subprocess.py:93} INFO - [0m02:55:20  13 of 15 ERROR creating sql table model analytics.AOV_category ................. [[31mERROR[0m in 0.50s]
[2025-09-10T02:55:20.155+0000] {subprocess.py:93} INFO - [0m02:55:20  14 of 15 ERROR creating sql table model analytics.AOV_product_name ............. [[31mERROR[0m in 0.41s]
[2025-09-10T02:55:21.839+0000] {subprocess.py:93} INFO - [0m02:55:21  15 of 15 OK created sql table model analytics.AVG_AOV_chek ..................... [[32mSELECT 16863[0m in 1.97s]
[2025-09-10T02:55:21.910+0000] {subprocess.py:93} INFO - [0m02:55:21
[2025-09-10T02:55:21.915+0000] {subprocess.py:93} INFO - [0m02:55:21  Finished running 7 view models, 8 table models in 0 hours 0 minutes and 6.41 seconds (6.41s).
[2025-09-10T02:55:21.989+0000] {subprocess.py:93} INFO - [0m02:55:21
[2025-09-10T02:55:21.995+0000] {subprocess.py:93} INFO - [0m02:55:21  [31mCompleted with 3 errors and 0 warnings:[0m
[2025-09-10T02:55:22.001+0000] {subprocess.py:93} INFO - [0m02:55:22
[2025-09-10T02:55:22.005+0000] {subprocess.py:93} INFO - [0m02:55:22    Database Error in model AOV_EBITDA_COUNT (models/marts/AOV_EBITDA_COUNT.sql)
[2025-09-10T02:55:22.008+0000] {subprocess.py:93} INFO -   type "avr_order_value" does not exist
[2025-09-10T02:55:22.013+0000] {subprocess.py:93} INFO -   LINE 26: order by avr_order_value
[2025-09-10T02:55:22.016+0000] {subprocess.py:93} INFO -                     ^
[2025-09-10T02:55:22.018+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_EBITDA_COUNT.sql
[2025-09-10T02:55:22.019+0000] {subprocess.py:93} INFO - [0m02:55:22
[2025-09-10T02:55:22.020+0000] {subprocess.py:93} INFO - [0m02:55:22    Database Error in model AOV_category (models/marts/AOV_category.sql)
[2025-09-10T02:55:22.022+0000] {subprocess.py:93} INFO -   type "avr_order_value" does not exist
[2025-09-10T02:55:22.023+0000] {subprocess.py:93} INFO -   LINE 27: order by avr_order_value
[2025-09-10T02:55:22.024+0000] {subprocess.py:93} INFO -                     ^
[2025-09-10T02:55:22.026+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_category.sql
[2025-09-10T02:55:22.027+0000] {subprocess.py:93} INFO - [0m02:55:22
[2025-09-10T02:55:22.028+0000] {subprocess.py:93} INFO - [0m02:55:22    Database Error in model AOV_product_name (models/marts/AOV_product_name.sql)
[2025-09-10T02:55:22.029+0000] {subprocess.py:93} INFO -   type "avr_order_value" does not exist
[2025-09-10T02:55:22.033+0000] {subprocess.py:93} INFO -   LINE 28: order by avr_order_value
[2025-09-10T02:55:22.034+0000] {subprocess.py:93} INFO -                     ^
[2025-09-10T02:55:22.036+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_product_name.sql
[2025-09-10T02:55:22.037+0000] {subprocess.py:93} INFO - [0m02:55:22
[2025-09-10T02:55:22.039+0000] {subprocess.py:93} INFO - [0m02:55:22  Done. PASS=12 WARN=0 ERROR=3 SKIP=0 TOTAL=15
[2025-09-10T02:55:32.470+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-10T02:55:32.470+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-10T02:55:32.482+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-10T02:55:32.487+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_run_models, task_id=run_dbt_models, run_id=manual__2025-09-10T02:55:08.278646+00:00, execution_date=20250910T025508, start_date=20250910T025510, end_date=20250910T025532
[2025-09-10T02:55:33.505+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1325 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 1.; 3418)
[2025-09-10T02:55:33.530+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-10T02:55:33.556+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-10T02:55:33.562+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
