[2025-08-21T07:10:37.418+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-21T07:10:37.445+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models manual__2025-08-21T07:10:35.658918+00:00 [queued]>
[2025-08-21T07:10:37.453+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models manual__2025-08-21T07:10:35.658918+00:00 [queued]>
[2025-08-21T07:10:37.454+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-21T07:10:37.473+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-08-21 07:10:35.658918+00:00
[2025-08-21T07:10:37.486+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_run_models', 'run_dbt_models', 'manual__2025-08-21T07:10:35.658918+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp9jpoqqpy']
[2025-08-21T07:10:37.487+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask run_dbt_models
[2025-08-21T07:10:37.486+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=55) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-21T07:10:37.488+0000] {standard_task_runner.py:64} INFO - Started process 56 to run task
[2025-08-21T07:10:37.502+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-08-21T07:10:37.575+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_models.run_dbt_models manual__2025-08-21T07:10:35.658918+00:00 [running]> on host 71579c071e19
[2025-08-21T07:10:37.769+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_run_models' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-08-21T07:10:35.658918+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-21T07:10:35.658918+00:00'
[2025-08-21T07:10:37.770+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-21T07:10:37.783+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-21T07:10:37.784+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /usr/app &&         dbt run --profiles-dir /usr/app\n        ']
[2025-08-21T07:10:37.797+0000] {subprocess.py:86} INFO - Output:
[2025-08-21T07:10:37.800+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 2: dbt: command not found
[2025-08-21T07:10:37.801+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-08-21T07:10:37.801+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-21T07:10:37.814+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-08-21T07:10:37.820+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_run_models, task_id=run_dbt_models, run_id=manual__2025-08-21T07:10:35.658918+00:00, execution_date=20250821T071035, start_date=20250821T071037, end_date=20250821T071037
[2025-08-21T07:10:37.850+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 58 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 127.; 56)
[2025-08-21T07:10:37.866+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-21T07:10:37.905+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-21T07:10:37.908+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
