[2025-08-25T15:00:04.018+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-25T15:00:04.173+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [queued]>
[2025-08-25T15:00:04.206+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [queued]>
[2025-08-25T15:00:04.207+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-25T15:00:04.253+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_new_data> on 2025-08-25 14:00:00+00:00
[2025-08-25T15:00:04.281+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=782) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-25T15:00:04.294+0000] {standard_task_runner.py:64} INFO - Started process 789 to run task
[2025-08-25T15:00:04.296+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'daily_generate_orders', 'generate_new_data', 'scheduled__2025-08-25T14:00:00+00:00', '--job-id', '522', '--raw', '--subdir', 'DAGS_FOLDER/generate_fake_shop_csv.py', '--cfg-path', '/tmp/tmp94fax127']
[2025-08-25T15:00:04.303+0000] {standard_task_runner.py:91} INFO - Job 522: Subtask generate_new_data
[2025-08-25T15:00:04.353+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-08-25T15:00:04.474+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [running]> on host b5ea13053d47
[2025-08-25T15:00:04.795+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='daily_generate_orders' AIRFLOW_CTX_TASK_ID='generate_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-25T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-25T14:00:00+00:00'
[2025-08-25T15:00:04.796+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-25T15:00:05.214+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-25T15:00:05.214+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/generate_fake_shop_csv.py", line 57, in generate_new_data
    payments, payments_types = read_csv_with_types("payments.csv")
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/generate_fake_shop_csv.py", line 34, in read_csv_with_types
    df = pd.read_csv(file_path)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/plugins/payments.csv'
[2025-08-25T15:00:05.249+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=daily_generate_orders, task_id=generate_new_data, run_id=scheduled__2025-08-25T14:00:00+00:00, execution_date=20250825T140000, start_date=20250825T150004, end_date=20250825T150005
[2025-08-25T15:00:05.269+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 522 for task generate_new_data ([Errno 2] No such file or directory: '/opt/airflow/plugins/payments.csv'; 789)
[2025-08-25T15:00:05.281+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-25T15:00:05.330+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-25T15:00:05.350+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-25T15:07:11.228+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-25T15:07:11.287+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [queued]>
[2025-08-25T15:07:11.305+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [queued]>
[2025-08-25T15:07:11.306+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-25T15:07:11.350+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_new_data> on 2025-08-25 14:00:00+00:00
[2025-08-25T15:07:11.365+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=805) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-25T15:07:11.366+0000] {standard_task_runner.py:64} INFO - Started process 807 to run task
[2025-08-25T15:07:11.370+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'daily_generate_orders', 'generate_new_data', 'scheduled__2025-08-25T14:00:00+00:00', '--job-id', '524', '--raw', '--subdir', 'DAGS_FOLDER/generate_fake_shop_csv.py', '--cfg-path', '/tmp/tmp0b27e7ab']
[2025-08-25T15:07:11.379+0000] {standard_task_runner.py:91} INFO - Job 524: Subtask generate_new_data
[2025-08-25T15:07:11.412+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-08-25T15:07:11.497+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [running]> on host b5ea13053d47
[2025-08-25T15:07:11.609+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='daily_generate_orders' AIRFLOW_CTX_TASK_ID='generate_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-25T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-25T14:00:00+00:00'
[2025-08-25T15:07:11.611+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-25T15:07:11.741+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-25T15:07:11.742+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/generate_fake_shop_csv.py", line 67, in generate_new_data
    "status": cast_value_to_dtype(random.choice(["pending", "shipped", "delivered"]), orders_types["status"])
                                                                                      ~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'status'
[2025-08-25T15:07:11.764+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=daily_generate_orders, task_id=generate_new_data, run_id=scheduled__2025-08-25T14:00:00+00:00, execution_date=20250825T140000, start_date=20250825T150711, end_date=20250825T150711
[2025-08-25T15:07:11.791+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 524 for task generate_new_data ('status'; 807)
[2025-08-25T15:07:11.839+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-25T15:07:11.889+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-25T15:07:11.905+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-25T15:32:45.213+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-25T15:32:45.270+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [queued]>
[2025-08-25T15:32:45.278+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [queued]>
[2025-08-25T15:32:45.278+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-25T15:32:45.298+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_new_data> on 2025-08-25 14:00:00+00:00
[2025-08-25T15:32:45.306+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=811) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-25T15:32:45.307+0000] {standard_task_runner.py:64} INFO - Started process 813 to run task
[2025-08-25T15:32:45.311+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'daily_generate_orders', 'generate_new_data', 'scheduled__2025-08-25T14:00:00+00:00', '--job-id', '526', '--raw', '--subdir', 'DAGS_FOLDER/generate_fake_shop_csv.py', '--cfg-path', '/tmp/tmpamuh_78k']
[2025-08-25T15:32:45.317+0000] {standard_task_runner.py:91} INFO - Job 526: Subtask generate_new_data
[2025-08-25T15:32:45.340+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-08-25T15:32:45.431+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [running]> on host b5ea13053d47
[2025-08-25T15:32:45.595+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='daily_generate_orders' AIRFLOW_CTX_TASK_ID='generate_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-25T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-25T14:00:00+00:00'
[2025-08-25T15:32:45.596+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-25T15:32:45.864+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-25T15:32:45.865+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-25T15:32:45.876+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=daily_generate_orders, task_id=generate_new_data, run_id=scheduled__2025-08-25T14:00:00+00:00, execution_date=20250825T140000, start_date=20250825T153245, end_date=20250825T153245
[2025-08-25T15:32:45.925+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-08-25T15:32:45.980+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-25T15:32:45.988+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-25T15:39:11.274+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-25T15:39:11.370+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [queued]>
[2025-08-25T15:39:11.386+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [queued]>
[2025-08-25T15:39:11.386+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-25T15:39:11.422+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_new_data> on 2025-08-25 14:00:00+00:00
[2025-08-25T15:39:11.436+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=823) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-25T15:39:11.436+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'daily_generate_orders', 'generate_new_data', 'scheduled__2025-08-25T14:00:00+00:00', '--job-id', '530', '--raw', '--subdir', 'DAGS_FOLDER/generate_fake_shop_csv.py', '--cfg-path', '/tmp/tmpneono5xn']
[2025-08-25T15:39:11.438+0000] {standard_task_runner.py:91} INFO - Job 530: Subtask generate_new_data
[2025-08-25T15:39:11.438+0000] {standard_task_runner.py:64} INFO - Started process 825 to run task
[2025-08-25T15:39:11.465+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-08-25T15:39:11.532+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [running]> on host b5ea13053d47
[2025-08-25T15:39:11.655+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='daily_generate_orders' AIRFLOW_CTX_TASK_ID='generate_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-25T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-25T14:00:00+00:00'
[2025-08-25T15:39:11.657+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-25T15:39:12.346+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-25T15:39:12.347+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-25T15:39:12.362+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=daily_generate_orders, task_id=generate_new_data, run_id=scheduled__2025-08-25T14:00:00+00:00, execution_date=20250825T140000, start_date=20250825T153911, end_date=20250825T153912
[2025-08-25T15:39:12.423+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-08-25T15:39:12.443+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-25T15:39:12.447+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-25T15:42:39.454+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-25T15:42:39.522+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [queued]>
[2025-08-25T15:42:39.529+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [queued]>
[2025-08-25T15:42:39.530+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-25T15:42:39.567+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_new_data> on 2025-08-25 14:00:00+00:00
[2025-08-25T15:42:39.577+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=829) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-25T15:42:39.578+0000] {standard_task_runner.py:64} INFO - Started process 831 to run task
[2025-08-25T15:42:39.582+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'daily_generate_orders', 'generate_new_data', 'scheduled__2025-08-25T14:00:00+00:00', '--job-id', '532', '--raw', '--subdir', 'DAGS_FOLDER/generate_fake_shop_csv.py', '--cfg-path', '/tmp/tmpztkx4ph8']
[2025-08-25T15:42:39.584+0000] {standard_task_runner.py:91} INFO - Job 532: Subtask generate_new_data
[2025-08-25T15:42:39.599+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-08-25T15:42:39.647+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [running]> on host b5ea13053d47
[2025-08-25T15:42:39.800+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='daily_generate_orders' AIRFLOW_CTX_TASK_ID='generate_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-25T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-25T14:00:00+00:00'
[2025-08-25T15:42:39.802+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-25T15:42:40.507+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-25T15:42:40.508+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-25T15:42:40.524+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=daily_generate_orders, task_id=generate_new_data, run_id=scheduled__2025-08-25T14:00:00+00:00, execution_date=20250825T140000, start_date=20250825T154239, end_date=20250825T154240
[2025-08-25T15:42:40.557+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-08-25T15:42:40.599+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-25T15:42:40.603+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-25T15:46:53.070+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-25T15:46:53.108+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [queued]>
[2025-08-25T15:46:53.115+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [queued]>
[2025-08-25T15:46:53.116+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-25T15:46:53.130+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_new_data> on 2025-08-25 14:00:00+00:00
[2025-08-25T15:46:53.140+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=841) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-25T15:46:53.141+0000] {standard_task_runner.py:64} INFO - Started process 843 to run task
[2025-08-25T15:46:53.140+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'daily_generate_orders', 'generate_new_data', 'scheduled__2025-08-25T14:00:00+00:00', '--job-id', '536', '--raw', '--subdir', 'DAGS_FOLDER/generate_fake_shop_csv.py', '--cfg-path', '/tmp/tmpvhcuqu4u']
[2025-08-25T15:46:53.147+0000] {standard_task_runner.py:91} INFO - Job 536: Subtask generate_new_data
[2025-08-25T15:46:53.173+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-08-25T15:46:53.210+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [running]> on host b5ea13053d47
[2025-08-25T15:46:53.307+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='daily_generate_orders' AIRFLOW_CTX_TASK_ID='generate_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-25T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-25T14:00:00+00:00'
[2025-08-25T15:46:53.308+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-25T15:46:53.980+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-25T15:46:53.980+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-25T15:46:53.990+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=daily_generate_orders, task_id=generate_new_data, run_id=scheduled__2025-08-25T14:00:00+00:00, execution_date=20250825T140000, start_date=20250825T154653, end_date=20250825T154653
[2025-08-25T15:46:54.044+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-08-25T15:46:54.074+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-25T15:46:54.076+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-25T15:50:26.716+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-25T15:50:26.750+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [queued]>
[2025-08-25T15:50:26.768+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [queued]>
[2025-08-25T15:50:26.769+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-25T15:50:26.801+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_new_data> on 2025-08-25 14:00:00+00:00
[2025-08-25T15:50:26.810+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=859) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-25T15:50:26.811+0000] {standard_task_runner.py:64} INFO - Started process 861 to run task
[2025-08-25T15:50:26.816+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'daily_generate_orders', 'generate_new_data', 'scheduled__2025-08-25T14:00:00+00:00', '--job-id', '542', '--raw', '--subdir', 'DAGS_FOLDER/generate_fake_shop_csv.py', '--cfg-path', '/tmp/tmpf7ijhfrg']
[2025-08-25T15:50:26.821+0000] {standard_task_runner.py:91} INFO - Job 542: Subtask generate_new_data
[2025-08-25T15:50:26.843+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-08-25T15:50:26.909+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_generate_orders.generate_new_data scheduled__2025-08-25T14:00:00+00:00 [running]> on host b5ea13053d47
[2025-08-25T15:50:27.116+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='daily_generate_orders' AIRFLOW_CTX_TASK_ID='generate_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-25T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-25T14:00:00+00:00'
[2025-08-25T15:50:27.117+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-25T15:50:27.376+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-25T15:50:27.377+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-25T15:50:27.387+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=daily_generate_orders, task_id=generate_new_data, run_id=scheduled__2025-08-25T14:00:00+00:00, execution_date=20250825T140000, start_date=20250825T155026, end_date=20250825T155027
[2025-08-25T15:50:27.428+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-08-25T15:50:27.468+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-25T15:50:27.471+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
