[2025-09-09T20:00:02.666+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-09T20:00:02.791+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-09T19:00:00+00:00 [queued]>
[2025-09-09T20:00:02.830+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-09T19:00:00+00:00 [queued]>
[2025-09-09T20:00:02.831+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-09T20:00:02.913+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-09 19:00:00+00:00
[2025-09-09T20:00:02.944+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3063) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-09T20:00:02.947+0000] {standard_task_runner.py:64} INFO - Started process 3064 to run task
[2025-09-09T20:00:02.952+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_run_models', 'run_dbt_models', 'scheduled__2025-09-09T19:00:00+00:00', '--job-id', '1299', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp2sfknr0s']
[2025-09-09T20:00:02.955+0000] {standard_task_runner.py:91} INFO - Job 1299: Subtask run_dbt_models
[2025-09-09T20:00:03.003+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-09-09T20:00:03.132+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-09T19:00:00+00:00 [running]> on host b5ea13053d47
[2025-09-09T20:00:03.590+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_run_models' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-09T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-09T19:00:00+00:00'
[2025-09-09T20:00:03.592+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-09T20:00:03.668+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-09T20:00:03.670+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /usr/app &&         dbt run --profiles-dir /usr/app\n        ']
[2025-09-09T20:00:03.710+0000] {subprocess.py:86} INFO - Output:
[2025-09-09T20:00:09.694+0000] {subprocess.py:93} INFO - [0m20:00:09  Running with dbt=1.7.9
[2025-09-09T20:00:10.075+0000] {subprocess.py:93} INFO - [0m20:00:10  Registered adapter: postgres=1.7.9
[2025-09-09T20:00:10.124+0000] {subprocess.py:93} INFO - [0m20:00:10  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-09T20:00:10.124+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-09T20:00:10.124+0000] {subprocess.py:93} INFO - - models.my_project.sources
[2025-09-09T20:00:10.151+0000] {subprocess.py:93} INFO - [0m20:00:10  Found 15 models, 7 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-09-09T20:00:10.155+0000] {subprocess.py:93} INFO - [0m20:00:10
[2025-09-09T20:00:10.385+0000] {subprocess.py:93} INFO - [0m20:00:10  Concurrency: 4 threads (target='dev')
[2025-09-09T20:00:10.388+0000] {subprocess.py:93} INFO - [0m20:00:10
[2025-09-09T20:00:10.427+0000] {subprocess.py:93} INFO - [0m20:00:10  1 of 15 START sql view model analytics.stg_AOV ................................. [RUN]
[2025-09-09T20:00:10.433+0000] {subprocess.py:93} INFO - [0m20:00:10  2 of 15 START sql view model analytics.stg_order_count_year .................... [RUN]
[2025-09-09T20:00:10.436+0000] {subprocess.py:93} INFO - [0m20:00:10  3 of 15 START sql view model analytics.stg_order_details ....................... [RUN]
[2025-09-09T20:00:10.447+0000] {subprocess.py:93} INFO - [0m20:00:10  4 of 15 START sql view model analytics.stg_order_items ......................... [RUN]
[2025-09-09T20:00:11.074+0000] {subprocess.py:93} INFO - [0m20:00:11  4 of 15 OK created sql view model analytics.stg_order_items .................... [[32mCREATE VIEW[0m in 0.59s]
[2025-09-09T20:00:11.075+0000] {subprocess.py:93} INFO - [0m20:00:11  1 of 15 OK created sql view model analytics.stg_AOV ............................ [[32mCREATE VIEW[0m in 0.63s]
[2025-09-09T20:00:11.079+0000] {subprocess.py:93} INFO - [0m20:00:11  2 of 15 OK created sql view model analytics.stg_order_count_year ............... [[32mCREATE VIEW[0m in 0.60s]
[2025-09-09T20:00:11.090+0000] {subprocess.py:93} INFO - [0m20:00:11  3 of 15 OK created sql view model analytics.stg_order_details .................. [[32mCREATE VIEW[0m in 0.61s]
[2025-09-09T20:00:11.093+0000] {subprocess.py:93} INFO - [0m20:00:11  5 of 15 START sql view model analytics.stg_orders .............................. [RUN]
[2025-09-09T20:00:11.100+0000] {subprocess.py:93} INFO - [0m20:00:11  6 of 15 START sql view model analytics.stg_payments ............................ [RUN]
[2025-09-09T20:00:11.111+0000] {subprocess.py:93} INFO - [0m20:00:11  7 of 15 START sql view model analytics.stg_products ............................ [RUN]
[2025-09-09T20:00:11.120+0000] {subprocess.py:93} INFO - [0m20:00:11  8 of 15 START sql table model analytics.AOV_chek ............................... [RUN]
[2025-09-09T20:00:11.476+0000] {subprocess.py:93} INFO - [0m20:00:11  5 of 15 OK created sql view model analytics.stg_orders ......................... [[32mCREATE VIEW[0m in 0.36s]
[2025-09-09T20:00:11.523+0000] {subprocess.py:93} INFO - [0m20:00:11  9 of 15 START sql table model analytics.order_count_year ....................... [RUN]
[2025-09-09T20:00:11.557+0000] {subprocess.py:93} INFO - [0m20:00:11  6 of 15 OK created sql view model analytics.stg_payments ....................... [[32mCREATE VIEW[0m in 0.43s]
[2025-09-09T20:00:11.592+0000] {subprocess.py:93} INFO - [0m20:00:11  8 of 15 OK created sql table model analytics.AOV_chek .......................... [[32mSELECT 50[0m in 0.44s]
[2025-09-09T20:00:11.593+0000] {subprocess.py:93} INFO - [0m20:00:11  10 of 15 START sql table model analytics.order_count_year+month_diff ........... [RUN]
[2025-09-09T20:00:11.596+0000] {subprocess.py:93} INFO - [0m20:00:11  7 of 15 OK created sql view model analytics.stg_products ....................... [[32mCREATE VIEW[0m in 0.48s]
[2025-09-09T20:00:11.625+0000] {subprocess.py:93} INFO - [0m20:00:11  11 of 15 START sql table model analytics.orders_summary ........................ [RUN]
[2025-09-09T20:00:11.629+0000] {subprocess.py:93} INFO - [0m20:00:11  12 of 15 START sql table model analytics.AVG_AOV_chek .......................... [RUN]
[2025-09-09T20:00:11.984+0000] {subprocess.py:93} INFO - [0m20:00:11  9 of 15 OK created sql table model analytics.order_count_year .................. [[32mSELECT 4[0m in 0.43s]
[2025-09-09T20:00:12.006+0000] {subprocess.py:93} INFO - [0m20:00:12  13 of 15 START sql table model analytics.AOV_EBITDA_COUNT ...................... [RUN]
[2025-09-09T20:00:12.141+0000] {subprocess.py:93} INFO - [0m20:00:12  10 of 15 OK created sql table model analytics.order_count_year+month_diff ...... [[32mSELECT 28[0m in 0.53s]
[2025-09-09T20:00:12.142+0000] {subprocess.py:93} INFO - [0m20:00:12  11 of 15 OK created sql table model analytics.orders_summary ................... [[32mSELECT 10000[0m in 0.50s]
[2025-09-09T20:00:12.156+0000] {subprocess.py:93} INFO - [0m20:00:12  15 of 15 START sql table model analytics.AOV_product_name ...................... [RUN]
[2025-09-09T20:00:12.157+0000] {subprocess.py:93} INFO - [0m20:00:12  14 of 15 START sql table model analytics.AOV_category .......................... [RUN]
[2025-09-09T20:00:12.340+0000] {subprocess.py:93} INFO - [0m20:00:12  12 of 15 OK created sql table model analytics.AVG_AOV_chek ..................... [[32mSELECT 16839[0m in 0.70s]
[2025-09-09T20:00:12.370+0000] {subprocess.py:93} INFO - [0m20:00:12  13 of 15 ERROR creating sql table model analytics.AOV_EBITDA_COUNT ............. [[31mERROR[0m in 0.34s]
[2025-09-09T20:00:12.424+0000] {subprocess.py:93} INFO - [0m20:00:12  14 of 15 ERROR creating sql table model analytics.AOV_category ................. [[31mERROR[0m in 0.26s]
[2025-09-09T20:00:12.445+0000] {subprocess.py:93} INFO - [0m20:00:12  15 of 15 ERROR creating sql table model analytics.AOV_product_name ............. [[31mERROR[0m in 0.27s]
[2025-09-09T20:00:12.490+0000] {subprocess.py:93} INFO - [0m20:00:12
[2025-09-09T20:00:12.492+0000] {subprocess.py:93} INFO - [0m20:00:12  Finished running 7 view models, 8 table models in 0 hours 0 minutes and 2.33 seconds (2.33s).
[2025-09-09T20:00:12.520+0000] {subprocess.py:93} INFO - [0m20:00:12
[2025-09-09T20:00:12.521+0000] {subprocess.py:93} INFO - [0m20:00:12  [31mCompleted with 3 errors and 0 warnings:[0m
[2025-09-09T20:00:12.522+0000] {subprocess.py:93} INFO - [0m20:00:12
[2025-09-09T20:00:12.524+0000] {subprocess.py:93} INFO - [0m20:00:12    Database Error in model AOV_EBITDA_COUNT (models/marts/AOV_EBITDA_COUNT.sql)
[2025-09-09T20:00:12.524+0000] {subprocess.py:93} INFO -   type "avr_order_value" does not exist
[2025-09-09T20:00:12.524+0000] {subprocess.py:93} INFO -   LINE 19: order by avr_order_value
[2025-09-09T20:00:12.525+0000] {subprocess.py:93} INFO -                     ^
[2025-09-09T20:00:12.525+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_EBITDA_COUNT.sql
[2025-09-09T20:00:12.526+0000] {subprocess.py:93} INFO - [0m20:00:12
[2025-09-09T20:00:12.527+0000] {subprocess.py:93} INFO - [0m20:00:12    Database Error in model AOV_category (models/marts/AOV_category.sql)
[2025-09-09T20:00:12.528+0000] {subprocess.py:93} INFO -   type "avr_order_value" does not exist
[2025-09-09T20:00:12.528+0000] {subprocess.py:93} INFO -   LINE 21: order by avr_order_value
[2025-09-09T20:00:12.528+0000] {subprocess.py:93} INFO -                     ^
[2025-09-09T20:00:12.528+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_category.sql
[2025-09-09T20:00:12.529+0000] {subprocess.py:93} INFO - [0m20:00:12
[2025-09-09T20:00:12.530+0000] {subprocess.py:93} INFO - [0m20:00:12    Database Error in model AOV_product_name (models/marts/AOV_product_name.sql)
[2025-09-09T20:00:12.531+0000] {subprocess.py:93} INFO -   type "avr_order_value" does not exist
[2025-09-09T20:00:12.531+0000] {subprocess.py:93} INFO -   LINE 21: order by avr_order_value
[2025-09-09T20:00:12.531+0000] {subprocess.py:93} INFO -                     ^
[2025-09-09T20:00:12.531+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_product_name.sql
[2025-09-09T20:00:12.532+0000] {subprocess.py:93} INFO - [0m20:00:12
[2025-09-09T20:00:12.533+0000] {subprocess.py:93} INFO - [0m20:00:12  Done. PASS=12 WARN=0 ERROR=3 SKIP=0 TOTAL=15
[2025-09-09T20:00:22.946+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-09T20:00:22.947+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-09T20:00:22.970+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-09T20:00:22.975+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_run_models, task_id=run_dbt_models, run_id=scheduled__2025-09-09T19:00:00+00:00, execution_date=20250909T190000, start_date=20250909T200002, end_date=20250909T200022
[2025-09-09T20:00:22.990+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1299 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 1.; 3064)
[2025-09-09T20:00:23.008+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-09T20:00:23.068+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-09T20:00:23.072+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
