[2025-09-09T23:00:00.915+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-09T23:00:00.953+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-09T22:00:00+00:00 [queued]>
[2025-09-09T23:00:00.966+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-09T22:00:00+00:00 [queued]>
[2025-09-09T23:00:00.967+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-09T23:00:00.986+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-09 22:00:00+00:00
[2025-09-09T23:00:00.994+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3147) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-09T23:00:00.995+0000] {standard_task_runner.py:64} INFO - Started process 3148 to run task
[2025-09-09T23:00:00.999+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_run_models', 'run_dbt_models', 'scheduled__2025-09-09T22:00:00+00:00', '--job-id', '1305', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpnijoq1c4']
[2025-09-09T23:00:01.001+0000] {standard_task_runner.py:91} INFO - Job 1305: Subtask run_dbt_models
[2025-09-09T23:00:01.038+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-09-09T23:00:01.120+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-09T22:00:00+00:00 [running]> on host b5ea13053d47
[2025-09-09T23:00:01.338+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_run_models' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-09T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-09T22:00:00+00:00'
[2025-09-09T23:00:01.339+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-09T23:00:01.355+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-09T23:00:01.356+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /usr/app &&         dbt run --profiles-dir /usr/app\n        ']
[2025-09-09T23:00:01.373+0000] {subprocess.py:86} INFO - Output:
[2025-09-09T23:00:04.719+0000] {subprocess.py:93} INFO - [0m23:00:04  Running with dbt=1.7.9
[2025-09-09T23:00:05.108+0000] {subprocess.py:93} INFO - [0m23:00:05  Registered adapter: postgres=1.7.9
[2025-09-09T23:00:05.156+0000] {subprocess.py:93} INFO - [0m23:00:05  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-09T23:00:05.157+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-09T23:00:05.157+0000] {subprocess.py:93} INFO - - models.my_project.sources
[2025-09-09T23:00:05.183+0000] {subprocess.py:93} INFO - [0m23:00:05  Found 15 models, 7 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-09-09T23:00:05.186+0000] {subprocess.py:93} INFO - [0m23:00:05
[2025-09-09T23:00:05.331+0000] {subprocess.py:93} INFO - [0m23:00:05  Concurrency: 4 threads (target='dev')
[2025-09-09T23:00:05.332+0000] {subprocess.py:93} INFO - [0m23:00:05
[2025-09-09T23:00:05.364+0000] {subprocess.py:93} INFO - [0m23:00:05  1 of 15 START sql view model analytics.stg_AOV ................................. [RUN]
[2025-09-09T23:00:05.365+0000] {subprocess.py:93} INFO - [0m23:00:05  2 of 15 START sql view model analytics.stg_order_count_year .................... [RUN]
[2025-09-09T23:00:05.368+0000] {subprocess.py:93} INFO - [0m23:00:05  3 of 15 START sql view model analytics.stg_order_details ....................... [RUN]
[2025-09-09T23:00:05.369+0000] {subprocess.py:93} INFO - [0m23:00:05  4 of 15 START sql view model analytics.stg_order_items ......................... [RUN]
[2025-09-09T23:00:06.031+0000] {subprocess.py:93} INFO - [0m23:00:06  3 of 15 OK created sql view model analytics.stg_order_details .................. [[32mCREATE VIEW[0m in 0.65s]
[2025-09-09T23:00:06.060+0000] {subprocess.py:93} INFO - [0m23:00:06  1 of 15 OK created sql view model analytics.stg_AOV ............................ [[32mCREATE VIEW[0m in 0.69s]
[2025-09-09T23:00:06.061+0000] {subprocess.py:93} INFO - [0m23:00:06  5 of 15 START sql view model analytics.stg_orders .............................. [RUN]
[2025-09-09T23:00:06.074+0000] {subprocess.py:93} INFO - [0m23:00:06  6 of 15 START sql view model analytics.stg_payments ............................ [RUN]
[2025-09-09T23:00:06.078+0000] {subprocess.py:93} INFO - [0m23:00:06  4 of 15 OK created sql view model analytics.stg_order_items .................... [[32mCREATE VIEW[0m in 0.69s]
[2025-09-09T23:00:06.089+0000] {subprocess.py:93} INFO - [0m23:00:06  2 of 15 OK created sql view model analytics.stg_order_count_year ............... [[32mCREATE VIEW[0m in 0.71s]
[2025-09-09T23:00:06.092+0000] {subprocess.py:93} INFO - [0m23:00:06  7 of 15 START sql view model analytics.stg_products ............................ [RUN]
[2025-09-09T23:00:06.121+0000] {subprocess.py:93} INFO - [0m23:00:06  8 of 15 START sql table model analytics.AOV_chek ............................... [RUN]
[2025-09-09T23:00:06.450+0000] {subprocess.py:93} INFO - [0m23:00:06  5 of 15 OK created sql view model analytics.stg_orders ......................... [[32mCREATE VIEW[0m in 0.38s]
[2025-09-09T23:00:06.484+0000] {subprocess.py:93} INFO - [0m23:00:06  6 of 15 OK created sql view model analytics.stg_payments ....................... [[32mCREATE VIEW[0m in 0.39s]
[2025-09-09T23:00:06.498+0000] {subprocess.py:93} INFO - [0m23:00:06  9 of 15 START sql table model analytics.order_count_year ....................... [RUN]
[2025-09-09T23:00:06.517+0000] {subprocess.py:93} INFO - [0m23:00:06  10 of 15 START sql table model analytics.order_count_year+month_diff ........... [RUN]
[2025-09-09T23:00:06.631+0000] {subprocess.py:93} INFO - [0m23:00:06  7 of 15 OK created sql view model analytics.stg_products ....................... [[32mCREATE VIEW[0m in 0.51s]
[2025-09-09T23:00:06.643+0000] {subprocess.py:93} INFO - [0m23:00:06  11 of 15 START sql table model analytics.orders_summary ........................ [RUN]
[2025-09-09T23:00:06.697+0000] {subprocess.py:93} INFO - [0m23:00:06  8 of 15 OK created sql table model analytics.AOV_chek .......................... [[32mSELECT 50[0m in 0.53s]
[2025-09-09T23:00:06.721+0000] {subprocess.py:93} INFO - [0m23:00:06  12 of 15 START sql table model analytics.AVG_AOV_chek .......................... [RUN]
[2025-09-09T23:00:07.027+0000] {subprocess.py:93} INFO - [0m23:00:07  9 of 15 OK created sql table model analytics.order_count_year .................. [[32mSELECT 4[0m in 0.51s]
[2025-09-09T23:00:07.072+0000] {subprocess.py:93} INFO - [0m23:00:07  13 of 15 START sql table model analytics.AOV_EBITDA_COUNT ...................... [RUN]
[2025-09-09T23:00:07.136+0000] {subprocess.py:93} INFO - [0m23:00:07  10 of 15 OK created sql table model analytics.order_count_year+month_diff ...... [[32mSELECT 28[0m in 0.59s]
[2025-09-09T23:00:07.164+0000] {subprocess.py:93} INFO - [0m23:00:07  14 of 15 START sql table model analytics.AOV_category .......................... [RUN]
[2025-09-09T23:00:07.187+0000] {subprocess.py:93} INFO - [0m23:00:07  11 of 15 OK created sql table model analytics.orders_summary ................... [[32mSELECT 10000[0m in 0.50s]
[2025-09-09T23:00:07.239+0000] {subprocess.py:93} INFO - [0m23:00:07  15 of 15 START sql table model analytics.AOV_product_name ...................... [RUN]
[2025-09-09T23:00:07.434+0000] {subprocess.py:93} INFO - [0m23:00:07  12 of 15 OK created sql table model analytics.AVG_AOV_chek ..................... [[32mSELECT 16839[0m in 0.70s]
[2025-09-09T23:00:07.512+0000] {subprocess.py:93} INFO - [0m23:00:07  13 of 15 ERROR creating sql table model analytics.AOV_EBITDA_COUNT ............. [[31mERROR[0m in 0.43s]
[2025-09-09T23:00:07.520+0000] {subprocess.py:93} INFO - [0m23:00:07  14 of 15 ERROR creating sql table model analytics.AOV_category ................. [[31mERROR[0m in 0.34s]
[2025-09-09T23:00:07.540+0000] {subprocess.py:93} INFO - [0m23:00:07  15 of 15 ERROR creating sql table model analytics.AOV_product_name ............. [[31mERROR[0m in 0.28s]
[2025-09-09T23:00:07.582+0000] {subprocess.py:93} INFO - [0m23:00:07
[2025-09-09T23:00:07.584+0000] {subprocess.py:93} INFO - [0m23:00:07  Finished running 7 view models, 8 table models in 0 hours 0 minutes and 2.39 seconds (2.39s).
[2025-09-09T23:00:07.630+0000] {subprocess.py:93} INFO - [0m23:00:07
[2025-09-09T23:00:07.632+0000] {subprocess.py:93} INFO - [0m23:00:07  [31mCompleted with 3 errors and 0 warnings:[0m
[2025-09-09T23:00:07.634+0000] {subprocess.py:93} INFO - [0m23:00:07
[2025-09-09T23:00:07.636+0000] {subprocess.py:93} INFO - [0m23:00:07    Database Error in model AOV_EBITDA_COUNT (models/marts/AOV_EBITDA_COUNT.sql)
[2025-09-09T23:00:07.637+0000] {subprocess.py:93} INFO -   type "avr_order_value" does not exist
[2025-09-09T23:00:07.637+0000] {subprocess.py:93} INFO -   LINE 19: order by avr_order_value
[2025-09-09T23:00:07.638+0000] {subprocess.py:93} INFO -                     ^
[2025-09-09T23:00:07.638+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_EBITDA_COUNT.sql
[2025-09-09T23:00:07.639+0000] {subprocess.py:93} INFO - [0m23:00:07
[2025-09-09T23:00:07.640+0000] {subprocess.py:93} INFO - [0m23:00:07    Database Error in model AOV_category (models/marts/AOV_category.sql)
[2025-09-09T23:00:07.640+0000] {subprocess.py:93} INFO -   type "avr_order_value" does not exist
[2025-09-09T23:00:07.641+0000] {subprocess.py:93} INFO -   LINE 21: order by avr_order_value
[2025-09-09T23:00:07.641+0000] {subprocess.py:93} INFO -                     ^
[2025-09-09T23:00:07.642+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_category.sql
[2025-09-09T23:00:07.642+0000] {subprocess.py:93} INFO - [0m23:00:07
[2025-09-09T23:00:07.643+0000] {subprocess.py:93} INFO - [0m23:00:07    Database Error in model AOV_product_name (models/marts/AOV_product_name.sql)
[2025-09-09T23:00:07.644+0000] {subprocess.py:93} INFO -   type "avr_order_value" does not exist
[2025-09-09T23:00:07.645+0000] {subprocess.py:93} INFO -   LINE 21: order by avr_order_value
[2025-09-09T23:00:07.646+0000] {subprocess.py:93} INFO -                     ^
[2025-09-09T23:00:07.646+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_product_name.sql
[2025-09-09T23:00:07.646+0000] {subprocess.py:93} INFO - [0m23:00:07
[2025-09-09T23:00:07.647+0000] {subprocess.py:93} INFO - [0m23:00:07  Done. PASS=12 WARN=0 ERROR=3 SKIP=0 TOTAL=15
[2025-09-09T23:00:18.253+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-09T23:00:18.255+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-09T23:00:18.288+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-09T23:00:18.299+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_run_models, task_id=run_dbt_models, run_id=scheduled__2025-09-09T22:00:00+00:00, execution_date=20250909T220000, start_date=20250909T230000, end_date=20250909T230018
[2025-09-09T23:00:18.319+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1305 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 1.; 3148)
[2025-09-09T23:00:18.354+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-09T23:00:18.390+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-09T23:00:18.394+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
