[2025-09-09T17:00:01.595+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-09T17:00:01.654+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-09T16:00:00+00:00 [queued]>
[2025-09-09T17:00:01.668+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-09T16:00:00+00:00 [queued]>
[2025-09-09T17:00:01.669+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-09T17:00:01.698+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-09 16:00:00+00:00
[2025-09-09T17:00:01.705+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=2972) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-09T17:00:01.706+0000] {standard_task_runner.py:64} INFO - Started process 2973 to run task
[2025-09-09T17:00:01.708+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_run_models', 'run_dbt_models', 'scheduled__2025-09-09T16:00:00+00:00', '--job-id', '1292', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp9livag4q']
[2025-09-09T17:00:01.709+0000] {standard_task_runner.py:91} INFO - Job 1292: Subtask run_dbt_models
[2025-09-09T17:00:01.736+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-09-09T17:00:01.802+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_models.run_dbt_models scheduled__2025-09-09T16:00:00+00:00 [running]> on host b5ea13053d47
[2025-09-09T17:00:01.995+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_run_models' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-09T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-09T16:00:00+00:00'
[2025-09-09T17:00:01.997+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-09T17:00:02.050+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-09T17:00:02.052+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /usr/app &&         dbt run --profiles-dir /usr/app\n        ']
[2025-09-09T17:00:02.077+0000] {subprocess.py:86} INFO - Output:
[2025-09-09T17:00:06.104+0000] {subprocess.py:93} INFO - [0m17:00:06  Running with dbt=1.7.9
[2025-09-09T17:00:06.487+0000] {subprocess.py:93} INFO - [0m17:00:06  Registered adapter: postgres=1.7.9
[2025-09-09T17:00:06.764+0000] {subprocess.py:93} INFO - [0m17:00:06  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-09T17:00:06.764+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-09T17:00:06.764+0000] {subprocess.py:93} INFO - - models.my_project.sources
[2025-09-09T17:00:06.833+0000] {subprocess.py:93} INFO - [0m17:00:06  Found 15 models, 7 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-09-09T17:00:06.844+0000] {subprocess.py:93} INFO - [0m17:00:06
[2025-09-09T17:00:07.103+0000] {subprocess.py:93} INFO - [0m17:00:07  Concurrency: 4 threads (target='dev')
[2025-09-09T17:00:07.104+0000] {subprocess.py:93} INFO - [0m17:00:07
[2025-09-09T17:00:07.131+0000] {subprocess.py:93} INFO - [0m17:00:07  1 of 15 START sql view model analytics.stg_AOV ................................. [RUN]
[2025-09-09T17:00:07.135+0000] {subprocess.py:93} INFO - [0m17:00:07  2 of 15 START sql view model analytics.stg_order_count_year .................... [RUN]
[2025-09-09T17:00:07.144+0000] {subprocess.py:93} INFO - [0m17:00:07  4 of 15 START sql view model analytics.stg_order_items ......................... [RUN]
[2025-09-09T17:00:07.152+0000] {subprocess.py:93} INFO - [0m17:00:07  3 of 15 START sql view model analytics.stg_order_details ....................... [RUN]
[2025-09-09T17:00:07.810+0000] {subprocess.py:93} INFO - [0m17:00:07  4 of 15 OK created sql view model analytics.stg_order_items .................... [[32mCREATE VIEW[0m in 0.62s]
[2025-09-09T17:00:07.845+0000] {subprocess.py:93} INFO - [0m17:00:07  5 of 15 START sql view model analytics.stg_orders .............................. [RUN]
[2025-09-09T17:00:07.858+0000] {subprocess.py:93} INFO - [0m17:00:07  2 of 15 OK created sql view model analytics.stg_order_count_year ............... [[32mCREATE VIEW[0m in 0.71s]
[2025-09-09T17:00:07.875+0000] {subprocess.py:93} INFO - [0m17:00:07  3 of 15 OK created sql view model analytics.stg_order_details .................. [[32mCREATE VIEW[0m in 0.67s]
[2025-09-09T17:00:07.881+0000] {subprocess.py:93} INFO - [0m17:00:07  6 of 15 START sql view model analytics.stg_payments ............................ [RUN]
[2025-09-09T17:00:07.917+0000] {subprocess.py:93} INFO - [0m17:00:07  1 of 15 OK created sql view model analytics.stg_AOV ............................ [[32mCREATE VIEW[0m in 0.75s]
[2025-09-09T17:00:07.941+0000] {subprocess.py:93} INFO - [0m17:00:07  7 of 15 START sql view model analytics.stg_products ............................ [RUN]
[2025-09-09T17:00:07.943+0000] {subprocess.py:93} INFO - [0m17:00:07  8 of 15 START sql table model analytics.order_count_year ....................... [RUN]
[2025-09-09T17:00:08.456+0000] {subprocess.py:93} INFO - [0m17:00:08  5 of 15 OK created sql view model analytics.stg_orders ......................... [[32mCREATE VIEW[0m in 0.58s]
[2025-09-09T17:00:08.497+0000] {subprocess.py:93} INFO - [0m17:00:08  9 of 15 START sql table model analytics.order_count_year+month_diff ............ [RUN]
[2025-09-09T17:00:08.500+0000] {subprocess.py:93} INFO - [0m17:00:08  6 of 15 OK created sql view model analytics.stg_payments ....................... [[32mCREATE VIEW[0m in 0.60s]
[2025-09-09T17:00:08.514+0000] {subprocess.py:93} INFO - [0m17:00:08  7 of 15 OK created sql view model analytics.stg_products ....................... [[32mCREATE VIEW[0m in 0.54s]
[2025-09-09T17:00:08.558+0000] {subprocess.py:93} INFO - [0m17:00:08  10 of 15 START sql table model analytics.AOV_chek .............................. [RUN]
[2025-09-09T17:00:08.564+0000] {subprocess.py:93} INFO - [0m17:00:08  11 of 15 START sql table model analytics.orders_summary ........................ [RUN]
[2025-09-09T17:00:08.637+0000] {subprocess.py:93} INFO - [0m17:00:08  8 of 15 OK created sql table model analytics.order_count_year .................. [[32mSELECT 4[0m in 0.68s]
[2025-09-09T17:00:08.686+0000] {subprocess.py:93} INFO - [0m17:00:08  12 of 15 START sql table model analytics.AOV_EBITDA_COUNT ...................... [RUN]
[2025-09-09T17:00:09.065+0000] {subprocess.py:93} INFO - [0m17:00:09  12 of 15 ERROR creating sql table model analytics.AOV_EBITDA_COUNT ............. [[31mERROR[0m in 0.36s]
[2025-09-09T17:00:09.090+0000] {subprocess.py:93} INFO - [0m17:00:09  13 of 15 START sql table model analytics.AOV_category .......................... [RUN]
[2025-09-09T17:00:09.103+0000] {subprocess.py:93} INFO - [0m17:00:09  10 of 15 OK created sql table model analytics.AOV_chek ......................... [[32mSELECT 50[0m in 0.52s]
[2025-09-09T17:00:09.105+0000] {subprocess.py:93} INFO - [0m17:00:09  9 of 15 OK created sql table model analytics.order_count_year+month_diff ....... [[32mSELECT 28[0m in 0.58s]
[2025-09-09T17:00:09.128+0000] {subprocess.py:93} INFO - [0m17:00:09  11 of 15 OK created sql table model analytics.orders_summary ................... [[32mSELECT 10000[0m in 0.55s]
[2025-09-09T17:00:09.131+0000] {subprocess.py:93} INFO - [0m17:00:09  14 of 15 START sql table model analytics.AOV_product_name ...................... [RUN]
[2025-09-09T17:00:09.132+0000] {subprocess.py:93} INFO - [0m17:00:09  15 of 15 START sql table model analytics.AVG_AOV_chek .......................... [RUN]
[2025-09-09T17:00:09.281+0000] {subprocess.py:93} INFO - [0m17:00:09  13 of 15 ERROR creating sql table model analytics.AOV_category ................. [[31mERROR[0m in 0.17s]
[2025-09-09T17:00:09.305+0000] {subprocess.py:93} INFO - [0m17:00:09  14 of 15 ERROR creating sql table model analytics.AOV_product_name ............. [[31mERROR[0m in 0.16s]
[2025-09-09T17:00:09.466+0000] {subprocess.py:93} INFO - [0m17:00:09  15 of 15 OK created sql table model analytics.AVG_AOV_chek ..................... [[32mSELECT 16839[0m in 0.32s]
[2025-09-09T17:00:09.495+0000] {subprocess.py:93} INFO - [0m17:00:09
[2025-09-09T17:00:09.496+0000] {subprocess.py:93} INFO - [0m17:00:09  Finished running 7 view models, 8 table models in 0 hours 0 minutes and 2.65 seconds (2.65s).
[2025-09-09T17:00:09.512+0000] {subprocess.py:93} INFO - [0m17:00:09
[2025-09-09T17:00:09.513+0000] {subprocess.py:93} INFO - [0m17:00:09  [31mCompleted with 3 errors and 0 warnings:[0m
[2025-09-09T17:00:09.514+0000] {subprocess.py:93} INFO - [0m17:00:09
[2025-09-09T17:00:09.514+0000] {subprocess.py:93} INFO - [0m17:00:09    Database Error in model AOV_EBITDA_COUNT (models/marts/AOV_EBITDA_COUNT.sql)
[2025-09-09T17:00:09.514+0000] {subprocess.py:93} INFO -   type "avr_order_value" does not exist
[2025-09-09T17:00:09.515+0000] {subprocess.py:93} INFO -   LINE 19: order by avr_order_value
[2025-09-09T17:00:09.515+0000] {subprocess.py:93} INFO -                     ^
[2025-09-09T17:00:09.515+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_EBITDA_COUNT.sql
[2025-09-09T17:00:09.515+0000] {subprocess.py:93} INFO - [0m17:00:09
[2025-09-09T17:00:09.515+0000] {subprocess.py:93} INFO - [0m17:00:09    Database Error in model AOV_category (models/marts/AOV_category.sql)
[2025-09-09T17:00:09.516+0000] {subprocess.py:93} INFO -   type "avr_order_value" does not exist
[2025-09-09T17:00:09.516+0000] {subprocess.py:93} INFO -   LINE 21: order by avr_order_value
[2025-09-09T17:00:09.516+0000] {subprocess.py:93} INFO -                     ^
[2025-09-09T17:00:09.516+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_category.sql
[2025-09-09T17:00:09.516+0000] {subprocess.py:93} INFO - [0m17:00:09
[2025-09-09T17:00:09.517+0000] {subprocess.py:93} INFO - [0m17:00:09    Database Error in model AOV_product_name (models/marts/AOV_product_name.sql)
[2025-09-09T17:00:09.517+0000] {subprocess.py:93} INFO -   type "avr_order_value" does not exist
[2025-09-09T17:00:09.517+0000] {subprocess.py:93} INFO -   LINE 21: order by avr_order_value
[2025-09-09T17:00:09.517+0000] {subprocess.py:93} INFO -                     ^
[2025-09-09T17:00:09.517+0000] {subprocess.py:93} INFO -   compiled Code at target/run/my_project/models/marts/AOV_product_name.sql
[2025-09-09T17:00:09.517+0000] {subprocess.py:93} INFO - [0m17:00:09
[2025-09-09T17:00:09.518+0000] {subprocess.py:93} INFO - [0m17:00:09  Done. PASS=12 WARN=0 ERROR=3 SKIP=0 TOTAL=15
[2025-09-09T17:00:19.997+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-09T17:00:19.998+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-09T17:00:20.036+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-09T17:00:20.055+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_run_models, task_id=run_dbt_models, run_id=scheduled__2025-09-09T16:00:00+00:00, execution_date=20250909T160000, start_date=20250909T170001, end_date=20250909T170020
[2025-09-09T17:00:20.087+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1292 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 1.; 2973)
[2025-09-09T17:00:20.130+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-09T17:00:20.197+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-09T17:00:20.201+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
