[2025-08-25T07:20:45.936+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-25T07:20:45.971+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models manual__2025-08-25T07:20:44.634042+00:00 [queued]>
[2025-08-25T07:20:45.993+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_models.run_dbt_models manual__2025-08-25T07:20:44.634042+00:00 [queued]>
[2025-08-25T07:20:45.994+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-25T07:20:46.027+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-08-25 07:20:44.634042+00:00
[2025-08-25T07:20:46.038+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-25T07:20:46.040+0000] {standard_task_runner.py:64} INFO - Started process 85 to run task
[2025-08-25T07:20:46.041+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_run_models', 'run_dbt_models', 'manual__2025-08-25T07:20:44.634042+00:00', '--job-id', '410', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpeg1gbobo']
[2025-08-25T07:20:46.043+0000] {standard_task_runner.py:91} INFO - Job 410: Subtask run_dbt_models
[2025-08-25T07:20:46.068+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-08-25T07:20:46.119+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_models.run_dbt_models manual__2025-08-25T07:20:44.634042+00:00 [running]> on host 6d66cfb6534c
[2025-08-25T07:20:46.325+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_run_models' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-08-25T07:20:44.634042+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-25T07:20:44.634042+00:00'
[2025-08-25T07:20:46.327+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-25T07:20:46.357+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-25T07:20:46.358+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /usr/app &&         dbt run --profiles-dir /usr/app\n        ']
[2025-08-25T07:20:46.372+0000] {subprocess.py:86} INFO - Output:
[2025-08-25T07:20:50.108+0000] {subprocess.py:93} INFO - [0m07:20:50  Running with dbt=1.7.9
[2025-08-25T07:20:50.113+0000] {subprocess.py:93} INFO - [0m07:20:50  Encountered an error:
[2025-08-25T07:20:50.113+0000] {subprocess.py:93} INFO - Runtime Error
[2025-08-25T07:20:50.114+0000] {subprocess.py:93} INFO -   Could not find profile named 'default'
[2025-08-25T07:20:51.039+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-25T07:20:51.040+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-25T07:20:51.053+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-25T07:20:51.058+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_run_models, task_id=run_dbt_models, run_id=manual__2025-08-25T07:20:44.634042+00:00, execution_date=20250825T072044, start_date=20250825T072045, end_date=20250825T072051
[2025-08-25T07:20:51.095+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 410 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 2.; 85)
[2025-08-25T07:20:51.106+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-25T07:20:51.134+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-25T07:20:51.136+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
